// File generated by FlutterFire CLI — PLACEHOLDERS for Poko & Friends.
// Replace by running `flutterfire configure` against a dedicated Firebase
// project (recommended: poko-and-friends) with Android package
// com.lazy_bear_club.poko_and_friends and iOS bundle
// com.lazybearclub.pokoAndFriends.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'run FlutterFire CLI after creating the iOS Firebase app.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run FlutterFire CLI after creating the macOS Firebase app.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run FlutterFire CLI after creating the Windows Firebase app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run FlutterFire CLI after creating the Linux Firebase app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// PLACEHOLDER — replace via FlutterFire; do not ship with Poko project ids.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME_ANDROID_API_KEY',
    appId: '1:REPLACE_ME:android:REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'poko-and-friends',
    storageBucket: 'poko-and-friends.firebasestorage.app',
  );
}
